#!/usr/bin/env bash
# mint-droidspaces installer
# Bootstraps a Linux Mint rootfs and generates a launcher you can run
# inside DroidSpaces (or any proot/chroot-capable Android environment).
#
# Usage:
#   ./install.sh [--release CODENAME] [--dir PATH]
#                [--backend auto|proot|chroot] [--arch amd64|arm64]
#
# Examples:
#   ./install.sh                          # Mint 22 (wilma), auto arch/backend
#   ./install.sh --release virginia       # Mint 21.3
#   MINT_RELEASE=virginia ./install.sh    # same via env
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/config/defaults.sh"
. "$HERE/scripts/common.sh"
. "$HERE/scripts/fetch-rootfs.sh"

# ---- args --------------------------------------------------------------

FORCE_ARCH=""
while [ $# -gt 0 ]; do
    case "$1" in
        --release) MINT_RELEASE="$2"; shift 2 ;;
        --dir)     INSTALL_DIR="$2";  shift 2 ;;
        --backend) BACKEND="$2";      shift 2 ;;
        --arch)    FORCE_ARCH="$2";   shift 2 ;;
        --distro)  DISTRO="$2";       shift 2 ;;
        -h|--help)
            sed -n '2,20p' "$0"; exit 0 ;;
        *) die "unknown option: $1" ;;
    esac
done

# ---- preflight ---------------------------------------------------------

detect_arch
[ -n "$FORCE_ARCH" ] && LXC_ARCH="$FORCE_ARCH"
# Mint is amd64-only upstream; on arm64 this swaps in Ubuntu noble (Mint's base).
pick_source

have tar || die "need 'tar' to extract the rootfs"
have xz  || warn "'xz' not found — tar may still handle .xz via liblzma; continuing"

# proot is the default path on an unrooted phone. We check for it early so
# the user isn't told to install it *after* a 200 MB download.
if [ "$BACKEND" != "chroot" ] && ! have proot; then
    if [ "$(id -u)" = "0" ] && [ "$BACKEND" = "auto" ]; then
        info "no proot but running as root — will use chroot"
        BACKEND=chroot
    else
        die "proot not found. Install it first:
       Termux/pkg:  pkg install proot
       Debian env:  apt install proot
     or run as root with --backend chroot"
    fi
fi

ROOTFS="$INSTALL_DIR/rootfs"
if [ -d "$ROOTFS" ] && [ -n "$(ls -A "$ROOTFS" 2>/dev/null || true)" ]; then
    warn "$ROOTFS already exists and is not empty."
    printf '    wipe and reinstall? [y/N] '
    read -r _ans
    case "$_ans" in
        y|Y) rm -rf "$ROOTFS" ;;
        *) die "aborted — nothing changed" ;;
    esac
fi

# ---- fetch + extract ---------------------------------------------------

resolve_rootfs_url
fetch_and_verify "$INSTALL_DIR/.cache"

info "extracting into $ROOTFS ..."
mkdir -p "$ROOTFS"
# --delay-directory-restore keeps proot happy about perms on Android FS;
# 2>/dev/null swallows the harmless "cannot change ownership" noise that
# unprivileged extraction always produces.
proot_extract() {
    # When we already have proot, extract under it so device-node and
    # ownership entries in the tarball don't error out.
    proot --link2symlink tar -C "$ROOTFS" -xf "$ROOTFS_TARBALL" \
        --exclude='dev' 2>/dev/null
}
if [ "$BACKEND" != "chroot" ] && have proot; then
    proot_extract || tar -C "$ROOTFS" -xf "$ROOTFS_TARBALL" --exclude='dev' 2>/dev/null || true
else
    tar -C "$ROOTFS" -xf "$ROOTFS_TARBALL" 2>/dev/null || true
fi
[ -x "$ROOTFS/bin/bash" ] || [ -e "$ROOTFS/bin/bash" ] || die "extraction looks wrong — no /bin/bash in rootfs"
ok "rootfs extracted"

# ---- guest network + hostname -----------------------------------------

mkdir -p "$ROOTFS/etc"
printf 'nameserver %s\n' "$GUEST_DNS" > "$ROOTFS/etc/resolv.conf"
grep -q '127.0.0.1' "$ROOTFS/etc/hosts" 2>/dev/null || \
    printf '127.0.0.1 localhost\n::1 localhost\n127.0.1.1 mint-droidspaces\n' > "$ROOTFS/etc/hosts"
printf 'mint-droidspaces\n' > "$ROOTFS/etc/hostname"

# ---- generate launcher -------------------------------------------------

LAUNCHER="$INSTALL_DIR/start.sh"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by mint-droidspaces/install.sh — launches the Mint rootfs.
# Regenerate with install.sh; edit by hand at your own risk.
set -eu

ROOTFS="$ROOTFS"
BACKEND="$BACKEND"

# Resolve auto backend at launch time (root state can differ per session).
if [ "\$BACKEND" = "auto" ]; then
    if [ "\$(id -u)" = "0" ] && command -v chroot >/dev/null 2>&1; then
        BACKEND=chroot
    else
        BACKEND=proot
    fi
fi

# Command to run inside the guest (default: an interactive login shell).
if [ \$# -eq 0 ]; then
    set -- /bin/bash --login
fi

GUEST_ENV=(/usr/bin/env -i \\
    HOME=/root \\
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \\
    TERM="\${TERM:-xterm-256color}" \\
    LANG=C.UTF-8 \\
    "\$@")

run_proot() {
    # Bind /sdcard only if the app can see it (DroidSpaces sandboxing varies).
    SDCARD_BIND=()
    [ -d /sdcard ] && SDCARD_BIND=(-b /sdcard)
    exec proot \\
        --kill-on-exit \\
        --link2symlink \\
        -0 \\
        -r "\$ROOTFS" \\
        -b /dev \\
        -b /proc \\
        -b /sys \\
        -b "\$ROOTFS/tmp:/dev/shm" \\
        "\${SDCARD_BIND[@]}" \\
        -w /root \\
        "\${GUEST_ENV[@]}"
}

run_chroot() {
    [ "\$(id -u)" = "0" ] || { echo "chroot backend needs root" >&2; exit 1; }
    for m in dev proc sys dev/pts; do
        mkdir -p "\$ROOTFS/\$m"
        mountpoint -q "\$ROOTFS/\$m" || mount --bind "/\$m" "\$ROOTFS/\$m" 2>/dev/null || true
    done
    cp /etc/resolv.conf "\$ROOTFS/etc/resolv.conf" 2>/dev/null || true
    trap 'for m in dev/pts sys proc dev; do umount "\$ROOTFS/\$m" 2>/dev/null || true; done' EXIT
    exec chroot "\$ROOTFS" "\${GUEST_ENV[@]}"
}

case "\$BACKEND" in
    proot)  run_proot ;;
    chroot) run_chroot ;;
    *) echo "unknown backend: \$BACKEND" >&2; exit 1 ;;
esac
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# ---- done --------------------------------------------------------------

ok "$SRC_DISTRO/$SRC_RELEASE ($LXC_ARCH) installed at $ROOTFS"
cat <<DONE

  Start it:            $LAUNCHER
  Run one command:     $LAUNCHER apt update
  Backend:             $BACKEND

  First time inside, refresh the package lists:
      apt update && apt -y upgrade

DONE
